version: "3.4"
services:
  #Nginx Service
  webserver:
    image: nginx:1.23.2
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./web_files:/usr/share/nginx/html
      - ./web_configs:/etc/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      # host:container
      #- "4200:80"
      - "80:80"
      #- "443:443"
    # environment:
    #   - NGINX_HOST=localhost
    #   - NGINX_PORT=80
  #Mysql DB
  # db:
  #   image: mysql:5.7
  #   container_name: Mysqldb
  #   restart: unless-stopped
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD_FILE: /run/secrets/db_password
  #   secrets:
  #     - db_root_password
  #     - db_password
# secrets:
#   db_password:
#     file: db_password.txt
#   db_root_password:
#     file: db_root_password.txt

# volumes:
#   web_configs:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/wilder/Documentos/work/docker/nginx/enginx'
